version: "3.3"
services:
  discovery:
    build:  ../../project-eureka-server
    ports:
      - "8761:8761"
    image: "discovery-service"
  product:
    build:  ../../Product
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8010:8010"
    image: "product-service"
  user:
    build: ../../UserService
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8811:8811"
    image: "user-service"
    depends_on:
      - product
      
  recommandation:
    build:  ../../product-recommandation
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8081:8081"
    image: "recommandation-service"
    depends_on:
      - user
  order:
    build: ../../Order
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8084:8084"
    image: "order-service"
    depends_on:
      - user  
  config:
    build: ../../project-config-server
    command: --spring.profiles.active=native --spring.cloud.config.server.native.searchLocations=/config
    volumes:
      - type: bind
        source: ../../project-config-server/src/main/resources/centralRepo
        target: /config
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
      - spring.profiles.active=native
    ports:
      - "8888:8888"
    image: "config-server"
  gateway:
    build: ../../project-gateway-server
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery:8761/eureka/
    ports:
      - "8762:8762"
    image: "gateway-server"